# Generated by Django 4.1.7 on 2023-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_useredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredit',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useredit',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
