# Generated by Django 4.1.7 on 2023-03-04 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_alter_useredit_location_alter_useredit_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEdit',
            new_name='UserExtra',
        ),
    ]
