# Generated by Django 4.1.7 on 2023-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_useredit_userextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatar/blank.png', null=True, upload_to='avatar'),
        ),
    ]
