# Generated by Django 4.1.7 on 2023-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product.png', null=True, upload_to='products/'),
        ),
    ]
