# Generated by Django 4.1.7 on 2023-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default_product.png', null=True, upload_to='products/'),
        ),
    ]
