# Generated by Django 4.1.7 on 2023-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_product.png', null=True, upload_to='products/'),
        ),
    ]
