# Generated by Django 4.1.7 on 2023-03-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date',)},
        ),
    ]
